FLOOD_ZONES = [
    {
        "id": 1,
        "name": "Houston East Basin",
        "state": "Texas",
        "county": "Harris County",
        "lat": 29.7604,
        "lng": -95.3698,
        "flood_probability": 0.89,
        "observation_confidence": 0.93,
        "rainfall_mm_24h": 148,
        "river_stage": "Above flood stage",
        "soil_saturation": 0.82,
        "terrain_slope": 1.7,
        "flow_accumulation_index": 0.91,
        "exposed_buildings": 18420,
        "estimated_population_exposed": 64200,
        "risk_level": "Severe",
        "label_quality": "High confidence SAR + gauge agreement",
    },
    {
        "id": 2,
        "name": "New Orleans North",
        "state": "Louisiana",
        "county": "Orleans Parish",
        "lat": 29.9511,
        "lng": -90.0715,
        "flood_probability": 0.78,
        "observation_confidence": 0.86,
        "rainfall_mm_24h": 118,
        "river_stage": "Rising",
        "soil_saturation": 0.76,
        "terrain_slope": 0.8,
        "flow_accumulation_index": 0.87,
        "exposed_buildings": 11300,
        "estimated_population_exposed": 39200,
        "risk_level": "High",
        "label_quality": "Medium-high confidence, partial sensor coverage",
    },
    {
        "id": 3,
        "name": "Miami-Dade Coastal Zone",
        "state": "Florida",
        "county": "Miami-Dade County",
        "lat": 25.7617,
        "lng": -80.1918,
        "flood_probability": 0.66,
        "observation_confidence": 0.79,
        "rainfall_mm_24h": 92,
        "river_stage": "Normal",
        "soil_saturation": 0.74,
        "terrain_slope": 0.5,
        "flow_accumulation_index": 0.69,
        "exposed_buildings": 8200,
        "estimated_population_exposed": 28800,
        "risk_level": "Moderate",
        "label_quality": "Moderate confidence, coastal backwater uncertainty",
    },
    {
        "id": 4,
        "name": "Sacramento Delta",
        "state": "California",
        "county": "Sacramento County",
        "lat": 38.5816,
        "lng": -121.4944,
        "flood_probability": 0.59,
        "observation_confidence": 0.74,
        "rainfall_mm_24h": 71,
        "river_stage": "Rising",
        "soil_saturation": 0.68,
        "terrain_slope": 1.2,
        "flow_accumulation_index": 0.73,
        "exposed_buildings": 5100,
        "estimated_population_exposed": 14300,
        "risk_level": "Watch",
        "label_quality": "Moderate confidence, requires field validation",
    },
]

ROAD_RISKS = [
    {
        "id": 1,
        "road": "I-10 East Segment",
        "zone": "Houston East Basin",
        "road_type": "Interstate",
        "blockage_probability": 0.84,
        "expected_delay_min": 78,
        "alternative_route_available": False,
        "status": "Likely Blocked",
    },
    {
        "id": 2,
        "road": "US-90 Industrial Corridor",
        "zone": "Houston East Basin",
        "road_type": "Federal Highway",
        "blockage_probability": 0.71,
        "expected_delay_min": 52,
        "alternative_route_available": True,
        "status": "High Risk",
    },
    {
        "id": 3,
        "road": "LA-46 Corridor",
        "zone": "New Orleans North",
        "road_type": "State Road",
        "blockage_probability": 0.69,
        "expected_delay_min": 44,
        "alternative_route_available": True,
        "status": "High Risk",
    },
    {
        "id": 4,
        "road": "US-1 Coastal Route",
        "zone": "Miami-Dade Coastal Zone",
        "road_type": "Federal Highway",
        "blockage_probability": 0.53,
        "expected_delay_min": 28,
        "alternative_route_available": True,
        "status": "Watch",
    },
    {
        "id": 5,
        "road": "CA-160 Delta Route",
        "zone": "Sacramento Delta",
        "road_type": "State Road",
        "blockage_probability": 0.47,
        "expected_delay_min": 22,
        "alternative_route_available": True,
        "status": "Monitor",
    },
]

CRITICAL_ASSETS = [
    {
        "id": 1,
        "asset": "Memorial Regional Hospital",
        "type": "Hospital",
        "zone": "Houston East Basin",
        "exposure_score": 0.81,
        "access_status": "Limited Access",
        "operational_priority": "Critical",
    },
    {
        "id": 2,
        "asset": "Houston East Fire Station 12",
        "type": "Fire Station",
        "zone": "Houston East Basin",
        "exposure_score": 0.74,
        "access_status": "At Risk",
        "operational_priority": "High",
    },
    {
        "id": 3,
        "asset": "New Orleans Substation 4",
        "type": "Power Substation",
        "zone": "New Orleans North",
        "exposure_score": 0.72,
        "access_status": "At Risk",
        "operational_priority": "High",
    },
    {
        "id": 4,
        "asset": "Miami Emergency Shelter A",
        "type": "Shelter",
        "zone": "Miami-Dade Coastal Zone",
        "exposure_score": 0.46,
        "access_status": "Accessible",
        "operational_priority": "Medium",
    },
    {
        "id": 5,
        "asset": "Sacramento Water Pump Station",
        "type": "Utility",
        "zone": "Sacramento Delta",
        "exposure_score": 0.58,
        "access_status": "Monitor",
        "operational_priority": "Medium",
    },
]

CUSTOMER_SEGMENTS = [
    {
        "segment": "Federal Emergency Management",
        "examples": "FEMA, DHS, federal disaster response teams",
        "need": "Near real-time impact intelligence for disaster declarations, rescue planning, and response coordination.",
        "value": "Faster operational awareness and better prioritization of high-impact zones.",
    },
    {
        "segment": "State and Local Emergency Agencies",
        "examples": "Texas, Florida, Louisiana, California, county EOCs",
        "need": "Road access, shelter access, critical asset exposure, and community isolation indicators.",
        "value": "Better resource positioning and lower response delay.",
    },
    {
        "segment": "Insurance and Reinsurance",
        "examples": "Property insurers, reinsurers, catastrophe response teams",
        "need": "Rapid flood extent, depth, exposure, and claims-severity indicators.",
        "value": "Faster claims triage and more accurate event loss estimation.",
    },
    {
        "segment": "Infrastructure and Utilities",
        "examples": "Power utilities, transport agencies, logistics operators",
        "need": "Asset exposure, crew routing, outage risk, and restoration planning.",
        "value": "Reduced downtime and improved operational continuity.",
    },
]

def compute_dashboard_summary():
    active_zones = len(FLOOD_ZONES)
    severe_zones = len([z for z in FLOOD_ZONES if z["risk_level"] in ["Severe", "High"]])
    roads_at_risk = len([r for r in ROAD_RISKS if r["blockage_probability"] >= 0.6])
    exposed_assets = len([a for a in CRITICAL_ASSETS if a["exposure_score"] >= 0.6])
    population = sum(z["estimated_population_exposed"] for z in FLOOD_ZONES)
    exposed_buildings = sum(z["exposed_buildings"] for z in FLOOD_ZONES)
    highest_zone = max(FLOOD_ZONES, key=lambda z: z["flood_probability"])
    avg_confidence = round(sum(z["observation_confidence"] for z in FLOOD_ZONES) / active_zones, 2)

    return {
        "active_flood_zones": active_zones,
        "severe_or_high_zones": severe_zones,
        "roads_at_risk": roads_at_risk,
        "critical_assets_exposed": exposed_assets,
        "estimated_population_exposed": population,
        "exposed_buildings": exposed_buildings,
        "average_observation_confidence": avg_confidence,
        "top_priority_zone": highest_zone["name"],
        "top_priority_reason": "Highest flood probability with strong observation confidence and major road-access disruption.",
    }

RECOMMENDATIONS = {
    "priority_zone": "Houston East Basin",
    "risk_posture": "Severe operational impact expected",
    "reason": "Highest flood probability, high observation confidence, major interstate blockage risk, and exposed hospital access.",
    "recommended_actions": [
        "Pre-position rescue and emergency medical units west of I-10 before access deteriorates.",
        "Flag I-10 East Segment as likely blocked and route crews through secondary corridors.",
        "Prioritize hospital access monitoring and coordinate with local emergency operations center.",
        "Issue insurer and public-sector impact alert for exposed buildings and high-confidence flood labels.",
        "Request additional SAR revisit or validation pass if model confidence changes below operational threshold.",
    ],
    "model_governance_note": "Recommendation is based on dummy data. In production, each action should include source lineage, observation confidence, timestamp, and hydrological validation evidence.",
}
